version: 2

workflows:
  version: 2
  build-test-lint:
    jobs:
      - mac
      - debian

jobs:
  mac:
    working_directory: ~/live-common
    macos:
      xcode: "10.2.1"
    steps:
      - checkout
      - run: node -v

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}-and-cli-{{ checksum "cli/yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile && cd cli && yarn install --frozen-lockfile && yarn global add yalc
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}-and-cli-{{ checksum "cli/yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ~/node_modules
            - ~/cli/node_modules

      - run: yarn ci-lint
      - run: yarn ci-test-common
      - run:
          command: yarn ci-test-cli
          no_output_timeout: 1h

  debian:
    working_directory: ~/live-common
    docker:
      - image: circleci/node:8-stretch-browsers
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y libudev-dev libusb-1.0-0-dev jq
      - run:
          name: Install latest yarn
          command: |
            curl -sS http://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - ;
            echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list ;
            sudo apt-get update && sudo apt-get install yarn
            sudo rm /usr/local/bin/yarn # remove docker yarn
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}-and-cli-{{ checksum "cli/yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile && cd cli && yarn install --frozen-lockfile && yarn global add yalc
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}-and-cli-{{ checksum "cli/yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ~/node_modules
            - ~/cli/node_modules

      - run: yarn ci-lint
      - run: yarn ci-test-common
      - run:
          command: yarn ci-test-cli
          no_output_timeout: 1h
