name: Build Mobie App

on:
  push:
    branches:
      - main
      - develop
    # paths:
    #   - apps/ledger-live-desktop/**
  pull_request:
    branches:
      - main
      - develop
    # paths:
    #   - apps/ledger-live-desktop/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "yolo"
