name: React Build

on:
  push:
    branches:
      - main
    paths:
      - "packages/react/**"
  pull_request:
    branches:
      - main
    paths:
      - "packages/react/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Install dependencies
        run: yarn --cwd packages/react install --focus
      - name: Linter
        run: yarn --cwd packages/react lint
      - name: Typecheck
        run: yarn --cwd packages/react typecheck
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Install dependencies
        run: yarn && yarn playwright install
      - name: Build packages
        run: yarn icons build && yarn shared build && yarn react prerelease
      - name: Run tests
        run: yarn test:react
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-run-data
          path: |
            tests/react.spec.js-snapshots/
            test-results/
